apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifications-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: notifications-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_SES_ACCESS_KEY_ID
      remoteRef:
        key: secret/prod/notifications-microservice
        property: AWS_SES_ACCESS_KEY_ID
    - secretKey: AWS_SES_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/prod/notifications-microservice
        property: AWS_SES_SECRET_ACCESS_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/notifications-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: SERVICE_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: SERVICE_TOKEN
    - secretKey: CLIPLOT_NOTIFICATIONS_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/cliplot-service
        property: NOTIFICATIONS_SERVICE_TOKEN
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: secret/prod/notifications-microservice
        property: PAYMENT_API_KEY
    - secretKey: PAYMENT_APPLICATION_ID
      remoteRef:
        key: secret/prod/notifications-microservice
        property: PAYMENT_APPLICATION_ID
    - secretKey: PAYMENT_WEBHOOK_API_KEY
      remoteRef:
        key: secret/prod/notifications-microservice
        property: PAYMENT_WEBHOOK_API_KEY
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: secret/prod/notifications-microservice
        property: SENDGRID_API_KEY
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: TELEGRAM_BOT_TOKEN
    - secretKey: WHATSAPP_ACCESS_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: WHATSAPP_ACCESS_TOKEN
    - secretKey: ORCHESTRATOR_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: ORCHESTRATOR_SERVICE_TOKEN
    - secretKey: AI_SERVICE_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: AI_SERVICE_TOKEN

    - secretKey: JWT_TOKEN
      remoteRef:
        key: secret/prod/notifications-microservice
        property: JWT_TOKEN
