#!/bin/bash

# Quick script to check S3 subscription status and provide next steps

echo "=========================================="
echo "S3 Subscription Status Check"
echo "=========================================="
echo ""

SUBSCRIPTION_ARN="arn:aws:sns:eu-central-1:781206275849:s3-email-events:fc776e48-1515-450b-9513-1e90b83e39f3"
WEBHOOK_ENDPOINT="https://notifications.statex.cz/email/inbound/s3"

echo "Subscription ARN: ${SUBSCRIPTION_ARN}"
echo "Webhook Endpoint: ${WEBHOOK_ENDPOINT}"
echo ""

echo "Since the subscription has been pending for 155+ minutes,"
echo "AWS SNS is likely unable to reach or validate the endpoint."
echo ""
echo "RECOMMENDED ACTION: Delete and recreate the subscription"
echo ""
echo "Steps:"
echo "1. Go to: https://eu-central-1.console.aws.amazon.com/sns/v3/home?region=eu-central-1#/topic/arn:aws:sns:eu-central-1:781206275849:s3-email-events"
echo "2. Click 'Subscriptions' tab"
echo "3. Find subscription for: ${WEBHOOK_ENDPOINT}"
echo "4. Click the checkbox next to it"
echo "5. Click 'Delete' button"
echo "6. Confirm deletion"
echo "7. Click 'Create subscription'"
echo "8. Configure:"
echo "   - Protocol: HTTPS"
echo "   - Endpoint: ${WEBHOOK_ENDPOINT}"
echo "   - ✅ Enable raw message delivery: YES (important!)"
echo "9. Click 'Create subscription'"
echo ""
echo "After recreating, AWS will send a NEW confirmation request immediately."
echo "Monitor logs to see it:"
echo "  ssh statex \"docker logs notifications-microservice-blue -f | grep -i 's3\|subscription'\""
echo ""
echo "The confirmation should happen within seconds after recreation."
echo ""
