#!/bin/bash

# Script to verify S3 Event Notification configuration
# This helps verify the setup is correct

set -e

echo "=========================================="
echo "S3 Event Notification Verification"
echo "=========================================="
echo ""

S3_BUCKET="speakasap-email-forward"
S3_PREFIX="forwards/"
SNS_TOPIC_NAME="s3-email-events-new"
WEBHOOK_ENDPOINT="https://notifications.statex.cz/email/inbound/s3"
AWS_REGION="eu-central-1"

echo "Configuration to verify:"
echo "  S3 Bucket: ${S3_BUCKET}"
echo "  S3 Prefix: ${S3_PREFIX}"
echo "  SNS Topic: ${SNS_TOPIC_NAME}"
echo "  Webhook: ${WEBHOOK_ENDPOINT}"
echo "  Region: ${AWS_REGION}"
echo ""

echo "=========================================="
echo "CHECKLIST - Verify in AWS Console"
echo "=========================================="
echo ""

echo "1. S3 Event Notification Configuration"
echo "   URL: https://${AWS_REGION}.console.aws.amazon.com/s3/buckets/${S3_BUCKET}?region=${AWS_REGION}&tab=properties"
echo ""
echo "   ✓ Scroll to 'Event notifications' section"
echo "   ✓ Check if event notification exists with:"
echo "     - Event name: ProcessInboundEmails (or similar)"
echo "     - Prefix: ${S3_PREFIX}"
echo "     - Event types: s3:ObjectCreated:Put, s3:ObjectCreated:CompleteMultipartUpload"
echo "     - Destination: SNS topic → ${SNS_TOPIC_NAME}"
echo ""

echo "2. SNS Topic Subscription"
echo "   URL: https://${AWS_REGION}.console.aws.amazon.com/sns/v3/home?region=${AWS_REGION}#/topics"
echo ""
echo "   ✓ Find topic: ${SNS_TOPIC_NAME}"
echo "   ✓ Click on topic → Subscriptions tab"
echo "   ✓ Verify subscription exists for: ${WEBHOOK_ENDPOINT}"
echo "   ✓ Check status: Should be 'Confirmed' (not Pending)"
echo "   ✓ Check 'Raw message delivery': Should be 'Enabled' or 'Yes'"
echo ""

echo "=========================================="
echo "Expected Configuration"
echo "=========================================="
echo ""

echo "S3 Event Notification should have:"
echo "  - Event name: ProcessInboundEmails"
echo "  - Prefix: ${S3_PREFIX}"
echo "  - Suffix: (empty)"
echo "  - Event types:"
echo "    ✅ s3:ObjectCreated:Put"
echo "    ✅ s3:ObjectCreated:CompleteMultipartUpload"
echo "  - Destination: SNS topic"
echo "  - SNS topic: ${SNS_TOPIC_NAME}"
echo ""

echo "SNS Subscription should have:"
echo "  - Protocol: HTTPS"
echo "  - Endpoint: ${WEBHOOK_ENDPOINT}"
echo "  - Status: Confirmed"
echo "  - Raw message delivery: Enabled"
echo ""

echo "=========================================="
echo "If Configuration is Missing"
echo "=========================================="
echo ""

echo "To create S3 Event Notification:"
echo "  1. Go to S3 Console → ${S3_BUCKET} → Properties"
echo "  2. Scroll to 'Event notifications'"
echo "  3. Click 'Create event notification'"
echo "  4. Configure as shown above"
echo "  5. Save changes"
echo ""

echo "To create SNS Subscription:"
echo "  1. Go to SNS Console → Topics → ${SNS_TOPIC_NAME}"
echo "  2. Click 'Create subscription'"
echo "  3. Protocol: HTTPS"
echo "  4. Endpoint: ${WEBHOOK_ENDPOINT}"
echo "  5. Enable raw message delivery: Yes"
echo "  6. Create subscription"
echo "  7. Service will auto-confirm"
echo ""

echo "=========================================="
echo "Testing"
echo "=========================================="
echo ""

echo "After verification, test with:"
echo "  1. Send email with attachment (>150 KB) to contact@speakasap.com"
echo "  2. Check service logs:"
echo "     docker logs notifications-microservice-blue --since '5 minutes ago' | grep -E 'S3_PROCESS|s3|bucket'"
echo "  3. Check database for the email"
echo ""
